### ISSUE TITLE
东财的日度资金流向接口，无法返回指定时间段的数据，数据未过滤

### ISSUE THREAD

**Issue by Snowfall-in-June** [1nchaos/adata#114]
stock_capital_flow_east.py 文件中
class StockCapitalFlowEast(StockCapitalFlowTemplate)下的方法
def get_capital_flow(self, stock_code: str = '000001', start_date=None, end_date=None)
start_date和end_date不生效，无法过滤出相关时间段的数据

**Comment by 1nchaos** [comment]
非常感谢，
更新到 2.7.2
