### ISSUE TITLE
挖掘新闻、网络文章和政策事件等

### ISSUE THREAD

**Issue by youzeliang** [1nchaos/adata#27]
挖掘新闻、网络文章和政策事件等
提到的这个，有啥好的数据来源什么的吗

**Comment by 1nchaos** [comment]
1. 核心是各大财经网站新闻，ZF官网，质量高的微信公众号等，并无特别渠道；
2. 对于普通投资者，当我们看到消息时，可能已经晚了一步；
3. 本项目的目的，主要通过舆情新闻判断热点事件的持续性和影响范围，进而确定投资主线，选择才是最重要。

**Comment by 1nchaos** [comment]
feature
