### ISSUE TITLE
requirements.txt 版本限制

### ISSUE THREAD

**Issue by LuneZ99** [1nchaos/adata#28]
requirements.txt 中限制的版本全部为限制小版本的形式，实际上该项目应该没有依赖特定版本的基础库，所以这些限制可以更宽松一些，或是使用更新的版本，避免和工作流中的其他版本产生冲突。例如 requests 已经更新至 `2.31.0`，则 `requests~=2.26.0` 可以更改为 `requests>=2.26.0`。
```
tqdm~=4.65.0
requests~=2.26.0
pandas~=1.5.3
beautifulsoup4~=4.11.2
py_mini_racer>=0.6.0
```

**Comment by 1nchaos** [comment]
1. 之前只考虑了版本的稳定性和独立使用的场景；
2. 仔细思考，既然作为开源，服务的是更多的场景，依赖增加兼容性会更好；
3. 感谢提的建议。
