### ISSUE TITLE
概念股的成分股是怎么取呢？

### ISSUE THREAD

**Issue by Gavin-yzg** [1nchaos/adata#36]
你好，我取概念股的成分股怎么都是空的，应该怎么取呢？

**Comment by 1nchaos** [comment]
1.先获取相应源的概念代码列表。
df = adata.stock.info.all_concept_code_east()
2.根据概念代码获取对应的概念成分股。
df = adata.stock.info.concept_constituent_east(concept_code="BK1104")
以上例子是东方财富的数据

**Comment by Gavin-yzg** [comment]
感谢，可以获取了
