### ISSUE TITLE
单只股票所属概念的接口会触发反爬的滑窗问题

### ISSUE THREAD

**Issue by LeslieWuboy** [1nchaos/adata#48]
stock.info.get_concept_ths() 会触发反爬机制，定期有一个滑动弹窗导致一直失败。

**Comment by 1nchaos** [comment]
目前可以先通过设置代理的方式进行数据获取，后续会升级替代方案等

**Comment by LeslieWuboy** [comment]
嗯嗯，最近还发现一个问题，就是指数的历史K线数据，传入k_type=1即日K线，但是返回的数据却不是固定日期的数据，这个接口可能也得稍作修改，麻烦您有空查阅一下，万分谢谢！



***@***.***
 
发件人： 1nchaos
发送时间： 2023-12-25 23:05
收件人： 1nchaos/adata
抄送： LeslieWuboy; Author
主题： Re: [1nchaos/adata] 单只股票所属概念的接口会触发反爬的滑窗问题 (Issue #48)
目前可以先通过设置代理的方式进行数据获取，后续会升级替代方案等

**Comment by 1nchaos** [comment]
这个问题更新到v1.2.3
