### ISSUE TITLE
获取历史行情数据-分钟数据

### ISSUE THREAD

**Issue by hanxuanliang** [1nchaos/adata#54]
新年快乐🎉！

如题：看目前提供的API中，能获取日线级别数据。但是30/60分钟级别数据无法获取，这个在一些中频策略中是个比较常见的数据源需求

**Comment by 1nchaos** [comment]
好的，感谢提供意见。后续会更新

**Comment by hanxuanliang** [comment]
目前对比了一些其他开源库，获取30分钟级别数据的时间range都比较短：

akshare: 2023-12-27 -> 2024-02-08

目前没有找到很好的方式能获取到1年范围小级别时间数据

**Comment by 1nchaos** [comment]
嗯，这个可以加交流群，使用其它实盘的数据
