### ISSUE TITLE
如何 查询 一段时期的 数据

### ISSUE THREAD

**Issue by akihara-sam** [1nchaos/adata#57]
获取股票的行情
获取到股票代码后，传入对应的stock_code参数，查询对应股票的行情信息。

import adata

# k_type: k线类型：1.日；2.周；3.月 默认：1 日k
res_df = adata.stock.market.get_market(stock_code='000001', k_type=1, start_date='2021-01-01')
print(res_df)

以上 start_date 是 查询开始日期 。有结束的日期的键值么？谢谢！

**Comment by 1nchaos** [comment]
1. 目前版本暂时没有 end_date 的参数，可以先获取到自行截取需要的范围数据。
2. 后续版本考虑增加对应的参数，方便灵活使用。

**Comment by 1nchaos** [comment]
跟新到版本2.5.0
