### ISSUE TITLE
能否新增行业分类

### ISSUE THREAD

**Issue by Zhongkai939** [1nchaos/adata#58]
您好，十分感谢您能公布开源接口，您的成果对我的帮助非常大！
能否新增中信或申万行业分类，及其成份股数据条款？
十分感谢。

**Comment by 1nchaos** [comment]
你好，想了解一下，你想用申万行业分类做什么

**Comment by Zhongkai939** [comment]
> 你好，想了解一下，你想用申万行业分类做什么

做一些行业的另类因子，比如市场情绪

**Comment by 1nchaos** [comment]
本项目的概念会比行业好很多，对于交易来说更适合。申万行业更适合研究，你可以参考这个项目：
https://akshare.akfamily.xyz/data/stock/stock.html#id246
