### ISSUE TITLE
获取历史数据不准确

### ISSUE THREAD

**Issue by REUZEE** [1nchaos/adata#61]
以中国石化 600028 为例，前面部分的价格为负数，是数据源的问题吗
 trade_time   open  close  ... pre_close stock_code  trade_date
0     2001-08-08 00:00:00  -1.86  -2.01  ...      0.00     600028  2001-08-08
1     2001-08-09 00:00:00  -2.02  -2.06  ...     -2.01     600028  2001-08-09
2     2001-08-10 00:00:00  -2.06  -2.02  ...     -2.06     600028  2001-08-10
3     2001-08-13 00:00:00  -2.03  -2.04  ...     -2.02     600028  2001-08-13
4     2001-08-14 00:00:00  -2.04  -2.06  ...     -2.04     600028  2001-08-14
...                   ...    ...    ...  ...       ...        ...         ...
5450  2024-04-15 00:00:00   6.39   6.65  ...      6.38     600028  2024-04-15
5451  2024-04-16 00:00:00   6.61   6.68  ...      6.65     600028  2024-04-16
5452  2024-04-17 00:00:00   6.64   6.64  ...      6.68     600028  2024-04-17
5453  2024-04-18 00:00:00   6.56   6.54  ...      6.64     600028  2024-04-18
5454  2024-04-19 00:00:00   6.53   6.67  ...      6.54     600028  2024-04-19

**Comment by 1nchaos** [comment]
你请求的是前复权的数据，前复权的数据有可能就是负的，这个不是问题
