### ISSUE TITLE
是否有按天获取所有股票的数据API？

### ISSUE THREAD

**Issue by yxm0513** [1nchaos/adata#66]
我把历史数据保存在了数据库，每天获取一天新的数据，现在要调用的API数量有点多，是否能实现一个API获取多个股票的当天数据？能拿到所有的当天数据。

**Comment by 1nchaos** [comment]
stock.market.list_market_current()
这个每天收盘的时候获取就是，一次性传多个

**Comment by yxm0513** [comment]
多谢
