### ISSUE TITLE
对部分股票调日线数据时报错

### ISSUE THREAD

**Issue by JackTheGrey** [1nchaos/adata#72]
对002824、002838-002860等股票调日线数据时出现ValueError 

报错代码：
`import adata
s_rixian = adata.stock.market.get_market(stock_code='002860', k_type=1, start_date='2017-01-01')
s_rixian`

报错详情如下：
<img width="388" alt="1e7cc9d3f43bd6a51e642afe23f6d6c" src="https://github.com/1nchaos/adata/assets/106424218/bd4c3d34-29f0-41ab-8a52-00472b395941">

疑似是在计算change_pct时的数据格式问题

**Comment by 1nchaos** [comment]
你好，你的环境依赖版本？应该是pandas版本问题
