### ISSUE TITLE
【bug】查询股票QQQ月度数据存在bug，只返回了后32条的数据，前面的数据没返回

### ISSUE THREAD

**Issue by komomoo** [1nchaos/adata#74]
```
import adata

res_df = adata.stock.market.get_market(stock_code="QQQ", k_type=3, start_date='2012-01-01')
print(res_df)
```
输出的截图如下，可以看到返回的数据不是从0开始的，只返回了后面的32条，前面的都没有：
<img width="1079" alt="image" src="https://github.com/1nchaos/adata/assets/13219417/693a49c7-40b0-4299-bde8-a86d555ab8f9">

**Comment by 1nchaos** [comment]
朋友，数据只有A股的数据，qqq这个代码A股没有呢

**Comment by komomoo** [comment]
> 朋友，数据只有A股的数据，qqq这个代码A股没有呢

但是可以查出数据呢，可不可以修复一下呀，返回一下完整的数据
