### ISSUE TITLE
资金流向-日度 stock.market.get_capital_flow()  存在单位转换问题。

### ISSUE THREAD

**Issue by LeslieWuboy** [1nchaos/adata#77]
**Describe the bug**
我在大批量获取资金流向日度数据时候，存在某些票由于价格单位是元，导致没有转换成浮点数。

**Expected behavior**
adata\common\utils\unit_conver.py 修改convert_to_yuan函数，增加对元的处理转换。
**Screenshots**
![1720108554934](https://github.com/1nchaos/adata/assets/66857794/3f896eb8-941e-4fc0-b88d-e9cb66d1aff8)
![1720108586399](https://github.com/1nchaos/adata/assets/66857794/61f29c17-de98-4cca-b68b-872fad981bbb)

**Comment by 1nchaos** [comment]
更新版本2.3.0
