### ISSUE TITLE
股票指数info接口数据缺失以及指数的分时、日度数据存在Nan问题

### ISSUE THREAD

**Issue by LeslieWuboy** [1nchaos/adata#79]
**Describe the bug**
1、股票指数info接口，目前只能取前250个指数，数量不齐全（默认只能取前五页，第六页开始跳转页面了，图1）
2、指数的分时、K线数据存在Nan问题（主要是第一天的涨跌幅可能存在Nan值未处理，图2）

**Expected behavior**
如图3所示，进行数值相关的列进行格式化。

**Screenshots**
![image](https://github.com/1nchaos/adata/assets/66857794/8a14b27c-1208-46d2-b21e-c39005f16ec2)
![1720200488437](https://github.com/1nchaos/adata/assets/66857794/bc8f0d9f-c16c-4258-a534-d8364f3b15ad)
![image](https://github.com/1nchaos/adata/assets/66857794/2c38c6d6-9724-43b2-b7aa-7b2c3b3339b7)

**Comment by 1nchaos** [comment]
更新到v2.3.1 指数的已经修复了
