### ISSUE TITLE
adata.stock.market.get_market_index(index_code='000001', start_date='2019-01-01',k_type=1)返回数据，部分交易日缺失

### ISSUE THREAD

**Issue by zpsakura** [1nchaos/adata#91]
大大，发现几个bug：

1 df = adata.stock.market.get_market_index(index_code='000001', start_date='2019-01-01',k_type=1)返回数据，部分交易日缺失,例如返回：
2019-01-02
2019-01-07
2019-01-10
2019-01-15
2019-01-18
2019-01-23
2019-01-28
缺少2019-01-03,2019-01-04等交易日数据。

2 stock.info.index_constituent()返回数据存在重复，返回550行，去重后300。结果正确，问题不大。

3 更新到2.5以后 stock.market.get_market() 返回 stock_code 字段没有了。

4 df = adata.stock.market.get_market_index_current(index_code='000001')
返回open,high,low,price,change没有小数点,例如返回287754，实际应该是2877.54。

**Comment by 1nchaos** [comment]
好的我先看看，234已经修复了，1可能是数据源的问题，我去核对一下

**Comment by 1nchaos** [comment]
之前接口做了数据压缩，现在展示了所有的，更新到v2.5.5

**Comment by zpsakura** [comment]
谢谢，大大
