### ISSUE TITLE
adata.fund.market.get_market_etf 部分代码返回空数据

### ISSUE THREAD

**Issue by Yzx-1024** [1nchaos/adata#98]
**Describe the bug**
adata.fund.market.get_market_etf  515670 517270 517760 159646 159693 159769 代码返回空数据

**To Reproduce**
配置python环境
安装adata包
执行：adata.fund.market.get_market_etf("515670")
得到空的dataframe

**Expected behavior**
获取行情数据

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by 1nchaos** [comment]
部分基金已经终止，其它基金数据，我再核实一下

**Comment by Yzx-1024** [comment]
确实是，bug close
